#!/usr/bin/env bash
###################################################################
# Script Name	: findshell                                                                                            
# Purpose	: Example script provide search options and copy 
#	          file for operator using menus.
# 		  You can also use this as custom shell
#		  Put it in /bin/findshell
#		  chsh --shell /bin/findshell <user_name>
# License       : license under GPL v3.0                                                                                         
# Author       	: Mohd Farhan Taib                                                
# Email         : mohdfarhantaib@gmail.com                                           
###################################################################

# capture CTRL+C, CTRL+Z and quit singles using the trap
trap '' SIGINT
trap '' SIGQUIT
trap '' SIGTSTP

# Declare the standard dir
# -> Change below directory according to your requirements.
loaddir(){
	DIR1="/apps/path_1"
	DIR2="/apps2/path_2"
	DIR3="/apps3/path_3"
	TGTDIR="/tmp/" # Or home directory
}
 
# Display message and pause 
pause(){
	local m="$@"
	echo "$m"
	read -p "Press [Enter] key to continue..." key
}

# remove file older then 3 days 
removeold_file(){
        loaddir
        find ${TGTDIR} -type f -name 'SAM-200-*-88ABC.*' -mtime +4 -exec echo "=> $(date)" \; -exec rm -v {} \; | tee -a ${TGTDIR}/findshell.log
}

# Search the file
search_file(){
	loaddir
	local PTN=""
	local EXT=""
	local FILES=""
	clear
	echo "
-----------------------------------------------------------------------
Please provide the pattern which consist of numbers, Example: 987312387
and the file extension or type, Example: pdf

File sample: SAM-200-[Pattern]-88ABC.[Extension]
-----------------------------------------------------------------------
"
	read -r -p "Enter the pattern : " PTN
	if [ $PTN = "cancel" ]; then return 0; fi
	local TRIM_PTN=$(echo $PTN | sed 's/[^0-9]*//g')
	read -r -p "Enter file extension [pdf|xlsx|zip|...] : " EXT
	local TRIM_EXT=$(echo $EXT | sed 's/[^a-zA-Z]*//g')
	echo -e "\nFinding the file, please wait...\n"

	local ARRAY=()
	while IFS=  read -r -d $'\0'; do
		ARRAY+=("$REPLY")
	done < <(find ${DIR1} ${DIR2} ${DIR3} -type f -name "SAM-200-${TRIM_PTN}-88ABC.${TRIM_EXT}" -print0)

	echo -e "Number\t| Folder" | column -s ',' -t
	echo -e "----------------"
	for KEY in "${!ARRAY[@]}"; do
		echo -e "$KEY\t| ${ARRAY[$KEY]}" | column -s ',' -t
	done
	
	if [ ${#ARRAY[@]} -eq 0 ]; then
		echo -e "\nFile not found"
	else
		echo ""
		read -r -p "Do you want to copy the file? [Y/n] : " YESNO
		if [ "$YESNO" = "Y" ] || [ "$YESNO" = "y" ]; then
		    local AA=1
		    while [[ "$AA" != "0" ]]; do
			echo ""
			read -r -p "Please provide the number based on the table above : " FILENUM
			if [ ! -z $FILENUM ] && (("$FILENUM" <= "$(echo ${#ARRAY[@]})")); then
			    echo -e "\nCopying the file to home...\n"
			    cp -v $(echo ${ARRAY[$FILENUM]}) $TGTDIR
			else
			    echo "Invalid number..."
			fi
			AA=0
		    done
		fi
	fi
}
 
##### Main #####

while :
do
	# show menu
	clear
	echo "---------------------------------"
	echo -e "\tM A I N - M E N U"
	echo "---------------------------------"
	echo "1. Show current date/time"
        echo "2. Search file"
	echo "3. remove older copied file"
	echo "4. List copied files"
	echo "5. Exit"
	echo "---------------------------------"
	read -r -p "Enter your choice [1-5] : " c
	# take action
	case $c in
		1) pause "$(date)";;
		2) search_file; pause;;
		3) removeold_file; pause;;
		4) echo -e "\nDirectory: $(pwd $TGTDIR)\n---------------------------------\n";
           	   ls -l $TGTDIR; pause;;
		5) break;;
		*) pause "Select between 1 to 5 only";;
	esac
done


##### End of Script #####
